### ISSUE TITLE
Clock disappears with numlock on

### ISSUE THREAD

**Issue by luispabon** [mortie/swaylock-effects#1]
When numlock is on, and indicator-caps-lock is active in swaylock, the clock disappears.

Config:
```
ignore-empty-password
font=Ubuntu

clock
timestr=%R
datestr=%a, %e of %B

screenshots

effect-blur=30x3
effect-greyscale
effect-scale=2

indicator
indicator-radius=240
indicator-thickness=20
indicator-caps-lock

key-hl-color=880033

separator-color=00000000

inside-color=00000088
inside-clear-color=ffd20400
inside-caps-lock-color=009ddc00
inside-ver-color=d9d8d800
inside-wrong-color=ee2e2400

ring-color=231f20D9
ring-clear-color=231f20D9
ring-caps-lock-color=231f20D9
ring-ver-color=231f20D9
ring-wrong-color=231f20D9

line-color=00000000
line-clear-color=ffd204FF
line-caps-lock-color=009ddcFF
line-ver-color=d9d8d8FF
line-wrong-color=ee2e24FF

text-clear-color=ffd20400
text-caps-lock-color=009ddc00
text-ver-color=d9d8d800
text-wrong-color=ee2e2400

bs-hl-color=ee2e24FF
caps-lock-key-hl-color=ffd204FF
caps-lock-bs-hl-color=ee2e24FF
```

**Comment by mortie** [comment]
So, I assume you mean caps lock and not numlock, because numlock dosn't sem to affect anything.

The reason this happens is that, when caps lock is enabled, it writes the text "caps lock" instead of the clock, but your `text-caps-lock-color` is `009ddc00`; that's transparent, since the alpha (last two characters) is `00`.

If you actually want to not show the caps lock text, the proper way to do that is to add `disable-caps-lock-text`, not to set `text-caps-lock-color` to transparent.

(Note that if you just add `disable-caps-lock-text` to your current config, the clock will also disappear when caps lock is active, because the clock will use `text-caps-lock-color` when caps lock is active and `text-caps-lock-color` is transparent.)

**Comment by luispabon** [comment]
I have the brain wiring of a goldfish. Of course, it is caps lock :man_facepalming: 

Closing as it's not an actual issue.

**Comment by luispabon** [comment]
changing title for future reference of anybody having the same issue
