### ISSUE TITLE
question: upstreaming to swaylock

### ISSUE THREAD

**Issue by aviau** [mortie/swaylock-effects#11]
Hello!

I am wondering if there are plans to upstream this to swaylock?

I'd consider uploading this to Debian repositories ( I am a Debian Developer), but I wouldn't need to do that if some of the swaylock-effects features got merged in swaylock.

Even if that is suboptimal, I might also prefer uploading a i3lock-fancy-like solution (script that takes a screenshot and passes it to swaylock) because it would probably require less maintenance and wouldn't fall out of sync with swaylock

**Comment by mortie** [comment]
I asked Drew informally on Mastodon shortly after I did the initial work on swaylock-effects: https://fosstodon.org/web/statuses/102335005617463328 - he replied that it's out of the scope of swaylock (though fwiw, whenever I fix something I think belongs in swaylock, I try to upstream it; see https://github.com/swaywm/swaylock/pull/96 and https://github.com/swaywm/swaylock/pull/91).

Regarding i3lock-fancy and efficiency: back when I used i3 and i3lock, I was annoyed that i3lock-fancy (and i3lock-fancy-rapid) spent so long encoding a 4k png just for i3lock to decode it again, so I wrote https://github.com/i3/i3lock/pull/226 to let i3lock read raw images instead of PNGs. As a result, as of https://github.com/yvbbrjdr/i3lock-fancy-rapid/pull/4, i3lock-fancy-rapid doesn't encode PNGs anymore. I decided against going with the same model for swaylock-effects though, because it would've been significantly more complex; while i3lock takes one image and displays it across all screens, swaylock takes one image per screen. A shell script can easily take a screenshot, apply effects with imagemagick, write raw rgb to stdout and pipe to i3lock, but you couldn't do the same with swaylock.

It might still be worth pursuing adding support for raw images to swaylock though. People wouldn't be able to make `scrot | imagemagick | i3lock` style scripts, but a dedicated "swaylock-fancy" program could still take the n individual screenshots for n screens, apply effects, and then pass them to swaylock, all without encoding and decoding PNGs.

Until and unless someone does that work however, it's reasonable to upload one of the existing programs which just take screenshots, do transformations, encode them as PNG, and launch swaylock. I will do my best to keep swaylock-effects reasonably up to date, but I understand your concerns about falling out of sync.

**Comment by luispabon** [comment]
My 2p: swaylock doesn't update nearly often enough for updates to become a problem.

For debian packaging though, I would imagine the problem with swaylock effects is that it conflicts with swaylock. That being said, that conflict can be declared during packaging can it not @aviau ? I would also love for this to go into debian as it'd go into Ubuntu right after - come Ubuntu 20.04 swaylock effects would be the only app I'd probably need to compile & package for myself.

**Comment by aviau** [comment]
Thank you mortie for your response.

@luispabon 

There would be no conflict as the two programs can have different names. I'd consider uploading but not before trying to ask upstream again, maybe they would consider the patch if they knew there was a lot of demand for it.

**Comment by mortie** [comment]
I don't feel like this is the kind of thing Swaylock would be interested in; they don't seem to be that receptive to feature requests. See https://github.com/swaywm/swaylock/issues/110, https://github.com/swaywm/swaylock/issues/100, https://github.com/swaywm/swaylock/issues/104, https://github.com/swaywm/swaylock/issues/38. #100's response is especially telling:

> Not interested in this feature or others like it - instead I encourage users to consider making a fork of swaylock which adds on more features like this. We want to keep swaylock simple.

And #38:

> Similar to i3lock-color's situation with upstream i3, we are not interested in tricking out swaylock with eye candy. However, again similar to i3lock-color, I encourage you to fork swaylock for your own needs.

I'm sure they're very aware of the demand for eye-candy, from long before swaylock-effects, but they don't want unnecessary complications in swaylock. Swaylock-effects is also fairly big, adding 748 lines (ignoring docs/readme changes), a dependency on the wlr-screencopy protocol, and a dependency on libopenmp, just for eye-candy.

It doesn't hurt to ask them if they would like to upstream swaylock-effects of course, but do you still think it's worthwhile?

**Comment by mortie** [comment]
What's the status on this?

By the way, I asked in #sway-devel, the response was indeed that it's probably out of scope for upstreaming.

**Comment by aviau** [comment]
I think that you have provided sufficident evidence that it won't be upstreamed. I'll go ahead and move on with the next steps for packaging swaylock.

**Comment by lechner** [comment]
Hi @aviau, I also miss these effects in Debian. A grace period is about productivity, and not eye candy. (As is [gammastep](https://bugs.debian.org/972131), which I packaged recently.) Maybe we could lean on upstream to accept at least some new features? Kind regards, Felix Lechner
