### ISSUE TITLE
Feature Request: Composite a logo onto a lockscreen image

### ISSUE THREAD

**Issue by danshick** [mortie/swaylock-effects#13]
It'd be nice to allow for some basic image compositing. Right now, I use the following helper script with the upstream swaylock. It takes a screenshot of the specified display, blurs it, and adds an icon/logo to the center of the blurred screenshot at 20% of the height of the screenshot. Ends up looking like [this](https://i.imgur.com/nFSiUEj.png).

<details><summary>lock.sh</summary>

```sh
#!/usr/bin/env sh

OVERLAY=~/.dotfiles/sway/images/_lock_img
WORKDIR=$(mktemp -d)
DISPLAY=${1}

grim -o "${DISPLAY}" - | mogrify -blur 0x5 png:- > $WORKDIR/lock_initial.png

if [ -f "$OVERLAY" ]; then
  HEIGHT_PERCENT=$(convert $WORKDIR/lock_initial.png -format "%[fx:0.2*h]" info:);
  convert -background transparent -density 400 -resize x$HEIGHT_PERCENT $OVERLAY png:- \
    | convert $WORKDIR/lock_initial.png png:- -gravity center -composite png:- > $WORKDIR/lock.png
else
  mv $WORKDIR/lock_initial.png $WORKDIR/lock.png;
fi

swaylock -u -i $WORKDIR/lock.png;
#rm -rf $WORKDIR;
exit 0;
```

</details>

This works fine, but imagemagick is a little slow. Is this something you'd be interested in adding?

**Comment by mortie** [comment]
Yeah, this would be cool. It shouldn't even be that hard to do.

I just need a syntax for how to specify where to put the image. Maybe something like: `--effect-compose '<X>,<Y>;<W>x<H>;<gravity>;<image path>'`, where:

* the `X` or `Y` can be negative to indicate offset from the right or bottom edge (like list subscripting in Python)
* The `W` and `H` is optional, defaulting to the width and height of the image
* Gravity can be like in ImageMagick (center, east, west, north, south, northeast, northwest, southeast, southwest), or be omitted, in which case it defaults to something sensible (top left if x/y are positive, top right if x is negative and y is positive, etc)

What do you think about that design? Are there any use cases I haven't thought about where that doesn't work? From what I can see, I think you should be able to use `--effect-compose "0,0;center;$OVERLAY"` if I implement this design.

**Comment by danshick** [comment]
I like this a lot. Only thing missing from what I'm doing today is scaling the composed image. Maybe if width or height could be percentage values of the screen size? Maybe if you only specify one or the other, it could preserve aspect ratio?

**Comment by mortie** [comment]
alright, this should work: https://github.com/mortie/swaylock-effects/commit/59943e4bdc25bf3a787dd002e142454c4052aedb

It should support SVGs, and I made it possible to specify x/y and w/h as percentages instead of pixels, so `swaylock --screenshots --effect-blur 5x3 --effect-compose "20%x20%;$HOME/.dotfiles/sway/images/_lock_img"` should do approximately what you want. Could you test that and verify that I haven't missed any important part of the feature?

The syntax turned out to be approximately how I outlined above; `<x>,<y>;<w>,<h>;<gravity>;<image path>`, where:

* The `x` and `y` can be a number of pixels, or a percentage of the screen's width/height. The `<x>,<y>` part is optional, and defaults to `50%,50%`.
* The `w` and `h` can be a number of pixels, or a percentage of the screen's width/height. The `<w>x<h>` part is optional, and defaults to `-1x-1` (which means the width/height of the image). If one of the dimensions is `-1`, it's given an automatic value based on the image's aspect ratio and the other dimension.
* `gravity` can be any of `center`, `north`, `south`, `east`, `west`, northeast`, `northwest`, `southeast` and `southwest`. It's optional, and is given a value of `center` if the `<x>,<y>` part isn't given, or an automatic value based on the x and y if the `<x>,<y>` part is present.

**Comment by danshick** [comment]
The compositing works great except for the gravity. Now I like it in the center so my default use case is fine, but I couldn't get it to do what was expected for any other value.

Separately, I can't get the blur effect to work at all, even without the compose part. Just combining screenshots and effect-blur seems not to work for me. Can you confirm? I can open a separate issue.

**Comment by mortie** [comment]
I may have misinterpreted what imagemagick's `gravity` option does. With my implementation, it chooses which point in the image you're placing at the desired position; for example, with the default options of `50%,50%;center`, the center of the image being composed is placed in the center of the screen. With the options `100%,100%;southeast`, the bottom right of the image is placed in the bottom right of the screen. `50%,50%;northwest` would put the top-left corner of the image in the center of the screen.

By the way, I found an issue with my north/south/east/west gravities; it makes sense for e.g `north` to control top center part of the image, but it used to control the top left part because of an oversight. That should be fixed in https://github.com/mortie/swaylock-effects/commit/3ada4c45bca4c6cdd6c27adf4fb8130b13228e2a. Maybe that caused the issue you saw? If not, I'd love a more detailed explanation of what it does wrong.

The blur effect works for me. However, the syntax is `--effect-blur <radius>x<iterations>`; I noticed that your imagemagick command uses `-blur 0x5`, but with swaylock-effect's blurring algorithm, `--effect-blur 0x5` means "Don't blur the image, 5 times in a row". Does it work if you do `swaylock --screenshots --effect-blur 5x5`? If not, can you post the exact command line you're running swaylock-effects with, and the exact output it produces (if any)?

**Comment by danshick** [comment]
Ah okay, then there is no bug in your gravity implementation. It works as you describe it. In fairness, I just use "Center" in my script and I don't have a specific desire to use the other options, but it is nice for others who many want more fine grained control over positioning. That said, I'm also not completely clear on how gravity works for ImageMagick.

The way I was thinking gravity would work is that it would set the starting position of the image to the top, top-right, right, bottom-right, bottom, bottom-left, left, or top-left position such that the image was still entirely "in bounds", and then the fine grained positioning arguments would effectively just be an offset from that starting position. Kind of like a float.

That said, I think I actually like this better. Gives you more fine grained control, especially with percentages being allowed not only for scaling, but also positioning.

Also, I must have had a typo because suddenly blur is working for me. I had retyped your example command the first time, but this time I copied it exactly and it worked, so I'm sure it was my fault.

Lastly, I gotta say, this runs so much faster than doing the image preprocessing with ImageMagick. Thanks for this.

**Comment by mortie** [comment]
I'm glad you find it useful :) And yeah, the performance is the reason I started with this lockscreen business in the first place; when you have a laptop, underclocked to save battery, with a 4k screen, and want the lock screen to show up at most a couple hundred milliseconds after hitting your lock hotkey, with a fancy blurring effect, you have to think about performance in a whole different way.
